/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellHelpsIndexRouteImport } from './routes/_shell/helps/index'
import { Route as ShellHelpsPageEditorRouteImport } from './routes/_shell/helps/page-editor'
import { Route as ShellPagesFooterIndexRouteImport } from './routes/_shell/pages/footer/index'
import { Route as ShellPagesFooterTemplateIdRouteImport } from './routes/_shell/pages/footer/$templateId'
import { Route as ShellPagesFooterNewRouteImport } from './routes/_shell/pages/footer/new'
import { Route as ShellPagesHeaderIndexRouteImport } from './routes/_shell/pages/header/index'
import { Route as ShellPagesHeaderTemplateIdRouteImport } from './routes/_shell/pages/header/$templateId'
import { Route as ShellPagesHeaderNewRouteImport } from './routes/_shell/pages/header/new'
import { Route as ShellPagesHomeIndexRouteImport } from './routes/_shell/pages/home/index'
import { Route as ShellPagesHomeTemplateIdRouteImport } from './routes/_shell/pages/home/$templateId'
import { Route as ShellPagesHomeNewRouteImport } from './routes/_shell/pages/home/new'

const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellHelpsIndexRoute = ShellHelpsIndexRouteImport.update({
  id: '/helps/',
  path: '/helps/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellHelpsPageEditorRoute = ShellHelpsPageEditorRouteImport.update({
  id: '/helps/page-editor',
  path: '/helps/page-editor',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPagesFooterIndexRoute = ShellPagesFooterIndexRouteImport.update({
  id: '/pages/footer/',
  path: '/pages/footer/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPagesFooterTemplateIdRoute =
  ShellPagesFooterTemplateIdRouteImport.update({
    id: '/pages/footer/$templateId',
    path: '/pages/footer/$templateId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellPagesFooterNewRoute = ShellPagesFooterNewRouteImport.update({
  id: '/pages/footer/new',
  path: '/pages/footer/new',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPagesHeaderIndexRoute = ShellPagesHeaderIndexRouteImport.update({
  id: '/pages/header/',
  path: '/pages/header/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPagesHeaderTemplateIdRoute =
  ShellPagesHeaderTemplateIdRouteImport.update({
    id: '/pages/header/$templateId',
    path: '/pages/header/$templateId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellPagesHeaderNewRoute = ShellPagesHeaderNewRouteImport.update({
  id: '/pages/header/new',
  path: '/pages/header/new',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPagesHomeIndexRoute = ShellPagesHomeIndexRouteImport.update({
  id: '/pages/home/',
  path: '/pages/home/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPagesHomeTemplateIdRoute =
  ShellPagesHomeTemplateIdRouteImport.update({
    id: '/pages/home/$templateId',
    path: '/pages/home/$templateId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellPagesHomeNewRoute = ShellPagesHomeNewRouteImport.update({
  id: '/pages/home/new',
  path: '/pages/home/new',
  getParentRoute: () => ShellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/helps/page-editor': typeof ShellHelpsPageEditorRoute
  '/helps/': typeof ShellHelpsIndexRoute
  '/pages/footer/$templateId': typeof ShellPagesFooterTemplateIdRoute
  '/pages/footer/new': typeof ShellPagesFooterNewRoute
  '/pages/header/$templateId': typeof ShellPagesHeaderTemplateIdRoute
  '/pages/header/new': typeof ShellPagesHeaderNewRoute
  '/pages/home/$templateId': typeof ShellPagesHomeTemplateIdRoute
  '/pages/home/new': typeof ShellPagesHomeNewRoute
  '/pages/footer/': typeof ShellPagesFooterIndexRoute
  '/pages/header/': typeof ShellPagesHeaderIndexRoute
  '/pages/home/': typeof ShellPagesHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/helps/page-editor': typeof ShellHelpsPageEditorRoute
  '/helps': typeof ShellHelpsIndexRoute
  '/pages/footer/$templateId': typeof ShellPagesFooterTemplateIdRoute
  '/pages/footer/new': typeof ShellPagesFooterNewRoute
  '/pages/header/$templateId': typeof ShellPagesHeaderTemplateIdRoute
  '/pages/header/new': typeof ShellPagesHeaderNewRoute
  '/pages/home/$templateId': typeof ShellPagesHomeTemplateIdRoute
  '/pages/home/new': typeof ShellPagesHomeNewRoute
  '/pages/footer': typeof ShellPagesFooterIndexRoute
  '/pages/header': typeof ShellPagesHeaderIndexRoute
  '/pages/home': typeof ShellPagesHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/helps/page-editor': typeof ShellHelpsPageEditorRoute
  '/_shell/helps/': typeof ShellHelpsIndexRoute
  '/_shell/pages/footer/$templateId': typeof ShellPagesFooterTemplateIdRoute
  '/_shell/pages/footer/new': typeof ShellPagesFooterNewRoute
  '/_shell/pages/header/$templateId': typeof ShellPagesHeaderTemplateIdRoute
  '/_shell/pages/header/new': typeof ShellPagesHeaderNewRoute
  '/_shell/pages/home/$templateId': typeof ShellPagesHomeTemplateIdRoute
  '/_shell/pages/home/new': typeof ShellPagesHomeNewRoute
  '/_shell/pages/footer/': typeof ShellPagesFooterIndexRoute
  '/_shell/pages/header/': typeof ShellPagesHeaderIndexRoute
  '/_shell/pages/home/': typeof ShellPagesHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/helps/page-editor'
    | '/helps/'
    | '/pages/footer/$templateId'
    | '/pages/footer/new'
    | '/pages/header/$templateId'
    | '/pages/header/new'
    | '/pages/home/$templateId'
    | '/pages/home/new'
    | '/pages/footer/'
    | '/pages/header/'
    | '/pages/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/helps/page-editor'
    | '/helps'
    | '/pages/footer/$templateId'
    | '/pages/footer/new'
    | '/pages/header/$templateId'
    | '/pages/header/new'
    | '/pages/home/$templateId'
    | '/pages/home/new'
    | '/pages/footer'
    | '/pages/header'
    | '/pages/home'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/'
    | '/_shell/helps/page-editor'
    | '/_shell/helps/'
    | '/_shell/pages/footer/$templateId'
    | '/_shell/pages/footer/new'
    | '/_shell/pages/header/$templateId'
    | '/_shell/pages/header/new'
    | '/_shell/pages/home/$templateId'
    | '/_shell/pages/home/new'
    | '/_shell/pages/footer/'
    | '/_shell/pages/header/'
    | '/_shell/pages/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/helps/': {
      id: '/_shell/helps/'
      path: '/helps'
      fullPath: '/helps/'
      preLoaderRoute: typeof ShellHelpsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/helps/page-editor': {
      id: '/_shell/helps/page-editor'
      path: '/helps/page-editor'
      fullPath: '/helps/page-editor'
      preLoaderRoute: typeof ShellHelpsPageEditorRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/footer/': {
      id: '/_shell/pages/footer/'
      path: '/pages/footer'
      fullPath: '/pages/footer/'
      preLoaderRoute: typeof ShellPagesFooterIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/footer/$templateId': {
      id: '/_shell/pages/footer/$templateId'
      path: '/pages/footer/$templateId'
      fullPath: '/pages/footer/$templateId'
      preLoaderRoute: typeof ShellPagesFooterTemplateIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/footer/new': {
      id: '/_shell/pages/footer/new'
      path: '/pages/footer/new'
      fullPath: '/pages/footer/new'
      preLoaderRoute: typeof ShellPagesFooterNewRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/header/': {
      id: '/_shell/pages/header/'
      path: '/pages/header'
      fullPath: '/pages/header/'
      preLoaderRoute: typeof ShellPagesHeaderIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/header/$templateId': {
      id: '/_shell/pages/header/$templateId'
      path: '/pages/header/$templateId'
      fullPath: '/pages/header/$templateId'
      preLoaderRoute: typeof ShellPagesHeaderTemplateIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/header/new': {
      id: '/_shell/pages/header/new'
      path: '/pages/header/new'
      fullPath: '/pages/header/new'
      preLoaderRoute: typeof ShellPagesHeaderNewRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/home/': {
      id: '/_shell/pages/home/'
      path: '/pages/home'
      fullPath: '/pages/home/'
      preLoaderRoute: typeof ShellPagesHomeIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/home/$templateId': {
      id: '/_shell/pages/home/$templateId'
      path: '/pages/home/$templateId'
      fullPath: '/pages/home/$templateId'
      preLoaderRoute: typeof ShellPagesHomeTemplateIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pages/home/new': {
      id: '/_shell/pages/home/new'
      path: '/pages/home/new'
      fullPath: '/pages/home/new'
      preLoaderRoute: typeof ShellPagesHomeNewRouteImport
      parentRoute: typeof ShellRouteRoute
    }
  }
}

interface ShellRouteRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellHelpsPageEditorRoute: typeof ShellHelpsPageEditorRoute
  ShellHelpsIndexRoute: typeof ShellHelpsIndexRoute
  ShellPagesFooterTemplateIdRoute: typeof ShellPagesFooterTemplateIdRoute
  ShellPagesFooterNewRoute: typeof ShellPagesFooterNewRoute
  ShellPagesHeaderTemplateIdRoute: typeof ShellPagesHeaderTemplateIdRoute
  ShellPagesHeaderNewRoute: typeof ShellPagesHeaderNewRoute
  ShellPagesHomeTemplateIdRoute: typeof ShellPagesHomeTemplateIdRoute
  ShellPagesHomeNewRoute: typeof ShellPagesHomeNewRoute
  ShellPagesFooterIndexRoute: typeof ShellPagesFooterIndexRoute
  ShellPagesHeaderIndexRoute: typeof ShellPagesHeaderIndexRoute
  ShellPagesHomeIndexRoute: typeof ShellPagesHomeIndexRoute
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellHelpsPageEditorRoute: ShellHelpsPageEditorRoute,
  ShellHelpsIndexRoute: ShellHelpsIndexRoute,
  ShellPagesFooterTemplateIdRoute: ShellPagesFooterTemplateIdRoute,
  ShellPagesFooterNewRoute: ShellPagesFooterNewRoute,
  ShellPagesHeaderTemplateIdRoute: ShellPagesHeaderTemplateIdRoute,
  ShellPagesHeaderNewRoute: ShellPagesHeaderNewRoute,
  ShellPagesHomeTemplateIdRoute: ShellPagesHomeTemplateIdRoute,
  ShellPagesHomeNewRoute: ShellPagesHomeNewRoute,
  ShellPagesFooterIndexRoute: ShellPagesFooterIndexRoute,
  ShellPagesHeaderIndexRoute: ShellPagesHeaderIndexRoute,
  ShellPagesHomeIndexRoute: ShellPagesHomeIndexRoute,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRouteRoute: ShellRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
