/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutHelpsIndexRouteImport } from './routes/_layout/helps/index'
import { Route as LayoutHelpsPageEditorRouteImport } from './routes/_layout/helps/page-editor'
import { Route as LayoutPagesFooterIndexRouteImport } from './routes/_layout/pages/footer/index'
import { Route as LayoutPagesFooterTemplateIdRouteImport } from './routes/_layout/pages/footer/$templateId'
import { Route as LayoutPagesFooterNewRouteImport } from './routes/_layout/pages/footer/new'
import { Route as LayoutPagesHeaderIndexRouteImport } from './routes/_layout/pages/header/index'
import { Route as LayoutPagesHeaderTemplateIdRouteImport } from './routes/_layout/pages/header/$templateId'
import { Route as LayoutPagesHeaderNewRouteImport } from './routes/_layout/pages/header/new'
import { Route as LayoutPagesHomeIndexRouteImport } from './routes/_layout/pages/home/index'
import { Route as LayoutPagesHomeTemplateIdRouteImport } from './routes/_layout/pages/home/$templateId'
import { Route as LayoutPagesHomeNewRouteImport } from './routes/_layout/pages/home/new'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutHelpsIndexRoute = LayoutHelpsIndexRouteImport.update({
  id: '/helps/',
  path: '/helps/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutHelpsPageEditorRoute = LayoutHelpsPageEditorRouteImport.update({
  id: '/helps/page-editor',
  path: '/helps/page-editor',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPagesFooterIndexRoute = LayoutPagesFooterIndexRouteImport.update({
  id: '/pages/footer/',
  path: '/pages/footer/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPagesFooterTemplateIdRoute =
  LayoutPagesFooterTemplateIdRouteImport.update({
    id: '/pages/footer/$templateId',
    path: '/pages/footer/$templateId',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutPagesFooterNewRoute = LayoutPagesFooterNewRouteImport.update({
  id: '/pages/footer/new',
  path: '/pages/footer/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPagesHeaderIndexRoute = LayoutPagesHeaderIndexRouteImport.update({
  id: '/pages/header/',
  path: '/pages/header/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPagesHeaderTemplateIdRoute =
  LayoutPagesHeaderTemplateIdRouteImport.update({
    id: '/pages/header/$templateId',
    path: '/pages/header/$templateId',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutPagesHeaderNewRoute = LayoutPagesHeaderNewRouteImport.update({
  id: '/pages/header/new',
  path: '/pages/header/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPagesHomeIndexRoute = LayoutPagesHomeIndexRouteImport.update({
  id: '/pages/home/',
  path: '/pages/home/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPagesHomeTemplateIdRoute =
  LayoutPagesHomeTemplateIdRouteImport.update({
    id: '/pages/home/$templateId',
    path: '/pages/home/$templateId',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutPagesHomeNewRoute = LayoutPagesHomeNewRouteImport.update({
  id: '/pages/home/new',
  path: '/pages/home/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/helps/page-editor': typeof LayoutHelpsPageEditorRoute
  '/helps/': typeof LayoutHelpsIndexRoute
  '/pages/footer/$templateId': typeof LayoutPagesFooterTemplateIdRoute
  '/pages/footer/new': typeof LayoutPagesFooterNewRoute
  '/pages/header/$templateId': typeof LayoutPagesHeaderTemplateIdRoute
  '/pages/header/new': typeof LayoutPagesHeaderNewRoute
  '/pages/home/$templateId': typeof LayoutPagesHomeTemplateIdRoute
  '/pages/home/new': typeof LayoutPagesHomeNewRoute
  '/pages/footer/': typeof LayoutPagesFooterIndexRoute
  '/pages/header/': typeof LayoutPagesHeaderIndexRoute
  '/pages/home/': typeof LayoutPagesHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/helps/page-editor': typeof LayoutHelpsPageEditorRoute
  '/helps': typeof LayoutHelpsIndexRoute
  '/pages/footer/$templateId': typeof LayoutPagesFooterTemplateIdRoute
  '/pages/footer/new': typeof LayoutPagesFooterNewRoute
  '/pages/header/$templateId': typeof LayoutPagesHeaderTemplateIdRoute
  '/pages/header/new': typeof LayoutPagesHeaderNewRoute
  '/pages/home/$templateId': typeof LayoutPagesHomeTemplateIdRoute
  '/pages/home/new': typeof LayoutPagesHomeNewRoute
  '/pages/footer': typeof LayoutPagesFooterIndexRoute
  '/pages/header': typeof LayoutPagesHeaderIndexRoute
  '/pages/home': typeof LayoutPagesHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/helps/page-editor': typeof LayoutHelpsPageEditorRoute
  '/_layout/helps/': typeof LayoutHelpsIndexRoute
  '/_layout/pages/footer/$templateId': typeof LayoutPagesFooterTemplateIdRoute
  '/_layout/pages/footer/new': typeof LayoutPagesFooterNewRoute
  '/_layout/pages/header/$templateId': typeof LayoutPagesHeaderTemplateIdRoute
  '/_layout/pages/header/new': typeof LayoutPagesHeaderNewRoute
  '/_layout/pages/home/$templateId': typeof LayoutPagesHomeTemplateIdRoute
  '/_layout/pages/home/new': typeof LayoutPagesHomeNewRoute
  '/_layout/pages/footer/': typeof LayoutPagesFooterIndexRoute
  '/_layout/pages/header/': typeof LayoutPagesHeaderIndexRoute
  '/_layout/pages/home/': typeof LayoutPagesHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/helps/page-editor'
    | '/helps/'
    | '/pages/footer/$templateId'
    | '/pages/footer/new'
    | '/pages/header/$templateId'
    | '/pages/header/new'
    | '/pages/home/$templateId'
    | '/pages/home/new'
    | '/pages/footer/'
    | '/pages/header/'
    | '/pages/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/helps/page-editor'
    | '/helps'
    | '/pages/footer/$templateId'
    | '/pages/footer/new'
    | '/pages/header/$templateId'
    | '/pages/header/new'
    | '/pages/home/$templateId'
    | '/pages/home/new'
    | '/pages/footer'
    | '/pages/header'
    | '/pages/home'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/helps/page-editor'
    | '/_layout/helps/'
    | '/_layout/pages/footer/$templateId'
    | '/_layout/pages/footer/new'
    | '/_layout/pages/header/$templateId'
    | '/_layout/pages/header/new'
    | '/_layout/pages/home/$templateId'
    | '/_layout/pages/home/new'
    | '/_layout/pages/footer/'
    | '/_layout/pages/header/'
    | '/_layout/pages/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/helps/': {
      id: '/_layout/helps/'
      path: '/helps'
      fullPath: '/helps/'
      preLoaderRoute: typeof LayoutHelpsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/helps/page-editor': {
      id: '/_layout/helps/page-editor'
      path: '/helps/page-editor'
      fullPath: '/helps/page-editor'
      preLoaderRoute: typeof LayoutHelpsPageEditorRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/footer/': {
      id: '/_layout/pages/footer/'
      path: '/pages/footer'
      fullPath: '/pages/footer/'
      preLoaderRoute: typeof LayoutPagesFooterIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/footer/$templateId': {
      id: '/_layout/pages/footer/$templateId'
      path: '/pages/footer/$templateId'
      fullPath: '/pages/footer/$templateId'
      preLoaderRoute: typeof LayoutPagesFooterTemplateIdRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/footer/new': {
      id: '/_layout/pages/footer/new'
      path: '/pages/footer/new'
      fullPath: '/pages/footer/new'
      preLoaderRoute: typeof LayoutPagesFooterNewRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/header/': {
      id: '/_layout/pages/header/'
      path: '/pages/header'
      fullPath: '/pages/header/'
      preLoaderRoute: typeof LayoutPagesHeaderIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/header/$templateId': {
      id: '/_layout/pages/header/$templateId'
      path: '/pages/header/$templateId'
      fullPath: '/pages/header/$templateId'
      preLoaderRoute: typeof LayoutPagesHeaderTemplateIdRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/header/new': {
      id: '/_layout/pages/header/new'
      path: '/pages/header/new'
      fullPath: '/pages/header/new'
      preLoaderRoute: typeof LayoutPagesHeaderNewRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/home/': {
      id: '/_layout/pages/home/'
      path: '/pages/home'
      fullPath: '/pages/home/'
      preLoaderRoute: typeof LayoutPagesHomeIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/home/$templateId': {
      id: '/_layout/pages/home/$templateId'
      path: '/pages/home/$templateId'
      fullPath: '/pages/home/$templateId'
      preLoaderRoute: typeof LayoutPagesHomeTemplateIdRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages/home/new': {
      id: '/_layout/pages/home/new'
      path: '/pages/home/new'
      fullPath: '/pages/home/new'
      preLoaderRoute: typeof LayoutPagesHomeNewRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutHelpsPageEditorRoute: typeof LayoutHelpsPageEditorRoute
  LayoutHelpsIndexRoute: typeof LayoutHelpsIndexRoute
  LayoutPagesFooterTemplateIdRoute: typeof LayoutPagesFooterTemplateIdRoute
  LayoutPagesFooterNewRoute: typeof LayoutPagesFooterNewRoute
  LayoutPagesHeaderTemplateIdRoute: typeof LayoutPagesHeaderTemplateIdRoute
  LayoutPagesHeaderNewRoute: typeof LayoutPagesHeaderNewRoute
  LayoutPagesHomeTemplateIdRoute: typeof LayoutPagesHomeTemplateIdRoute
  LayoutPagesHomeNewRoute: typeof LayoutPagesHomeNewRoute
  LayoutPagesFooterIndexRoute: typeof LayoutPagesFooterIndexRoute
  LayoutPagesHeaderIndexRoute: typeof LayoutPagesHeaderIndexRoute
  LayoutPagesHomeIndexRoute: typeof LayoutPagesHomeIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutHelpsPageEditorRoute: LayoutHelpsPageEditorRoute,
  LayoutHelpsIndexRoute: LayoutHelpsIndexRoute,
  LayoutPagesFooterTemplateIdRoute: LayoutPagesFooterTemplateIdRoute,
  LayoutPagesFooterNewRoute: LayoutPagesFooterNewRoute,
  LayoutPagesHeaderTemplateIdRoute: LayoutPagesHeaderTemplateIdRoute,
  LayoutPagesHeaderNewRoute: LayoutPagesHeaderNewRoute,
  LayoutPagesHomeTemplateIdRoute: LayoutPagesHomeTemplateIdRoute,
  LayoutPagesHomeNewRoute: LayoutPagesHomeNewRoute,
  LayoutPagesFooterIndexRoute: LayoutPagesFooterIndexRoute,
  LayoutPagesHeaderIndexRoute: LayoutPagesHeaderIndexRoute,
  LayoutPagesHomeIndexRoute: LayoutPagesHomeIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
