// 區塊庫入口:匯入即註冊所有自訂元素,並匯出契約 + 註冊表。
// 編輯器用它拿 schema(建表單)+ 掛自訂元素(即時預覽);
// 未來前台載同一包 WC 做互動。
export * from './contract'
export * from './events'
export * from './icons'
export { SfBlockElement } from './core/block-element'
export * from './core/registry'

export { SfContainer } from './blocks/layout/container'
export type { ContainerData } from './blocks/layout/container'
export { SfStack } from './blocks/layout/stack'
export type { StackData } from './blocks/layout/stack'
export { SfHeading } from './blocks/content/heading'
export type { HeadingData } from './blocks/content/heading'
export { SfText } from './blocks/content/text'
export type { TextData } from './blocks/content/text'
export { SfButton } from './blocks/content/button'
export type { ButtonData } from './blocks/content/button'
export { SfImage } from './blocks/content/image'
export type { ImageData } from './blocks/content/image'
export { SfIcon } from './blocks/content/icon'
export type { IconData } from './blocks/content/icon'
export { SfSpacer } from './blocks/separator/spacer'
export type { SpacerData } from './blocks/separator/spacer'
export { SfDivider } from './blocks/separator/divider'
export type { DividerData } from './blocks/separator/divider'
